# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60c0cede7203c09589f5c50c3dca2135c9fc1dfce8eed613bf261e628d91a6dafe29ece5c3dcde1baa17e93fc2821283c5c09b33d6e6fcbc7df87146e1885aa9

test:
  secret_key_base: 747324eb1c4f8a5a767abf55de537ec4ad4427313f7d0b7309c5989a50a6dc8a410db01d6d59abcb9e5e31adeaf44a9def9873b515eb803a26bc3a01fdda5e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
