# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
Admin.create!(email: 'stephenjamesdisalvio@gmail.com', password: 'dudewheresmycar', name: 'Stephen Di Salvio', phone_number: '201-572-2553', github: 'github.com/DiSalvio')

Project.create!(published: true, name: "Portfolio", description: "This is the first project I've deployed and is currently my main focus. It shows my preferred programming toolkit, a little about my coding background, descriptions of the projects I'm developing and designing, and a blog so I can post about my journey through the world of code.\n\nIn the future, I'll be able to upload music, photos, poems, short stories and videos to my Portfolio. Also, I'll expand my blog into sections so I have an outlet for my thoughts on a variety of topics. In terms of the bigger picture, my Portfolio serves as a testing ground for my ideas on how to make elements of the traditional multi-media blogging platform wholly customizable through the site UI by signing in as an admin.", features: ["Save blog posts as unpublished drafts", "Add topics to blog posts", "Text file uploads for blog", "Music file uploads", "Music downloads & UI", "Streaming music player", "Video file uploads", "Video downloads & UI", "Streaming video"])

Project.create!(published: true, name: "Bad Quarterback League", description: "Inspired by Grantland's BQBL, which was managed via Google Sheets, this project was intended to take all the fuss out of managing a fantasy BQBL. A league consists of 8-12 teams who each select 2-4 NFL teams' quarterbacks. There are weekly matchups, and a champion is crowned toward the end of the regular season. Points are determined by how dreadful your team's QBs play. Extra points for turnovers, sacks, low completion percentage, etc. Negative points for TDs, game-winning drives, high completion percentage, etc.\n\nEarly on I worked on this project alongside learning from tutorials and books on Rails (see Github page). After realizing that this was a little too complex for a first project, I postponed work until my Portfolio was up and running. I plan to deliver a working version by mid-August 2016, so it can be test-driven and improved during the 2016 NFL season.", features: ["Ability to create/join BQBLs", "Auto-generated draft order, weekly matchups, standings, and playoffs", "Customizable on-field and off-field scoring system", "On-field points determined by QB stats pulled from NFL API"])

Project.create!(published: true, name: "Election Projector", description: "The 2016 election projector allows you to create scenarios where candidates win different vote percentages in different state, and then automatically calculate the number of delegates they would receive as a result. Initially you can only create scenarios for the 2016 Democratic Primary election, but shortly after the initial release this will be updated to include the 2016 Republican Primary election and 2016 General election.", features: ["Create scenarios with any number of candidates and states", "Automatic delegate estimation & overall delegate totals", "Start with an initial delegate count"])
